name: Publish
on:
  workflow_call:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./dist

      - name: Install Dependencies
        run: npm ci

      - name: Publish Extension
        run: npx vsce publish -p ${{ secrets.AZURE_TOKEN }}
